### ISSUE TITLE
Easy way to strip cpccFileSystem off Unicode support?

### ISSUE THREAD

**Issue by IngwiePhoenix** [starmessage/cpcc#1]
Hey.

I wish to use cpccFileSystem as a stand-alone class in my application. I simply want to make the cross-platform work of handling files and folders easier in my project.

Kind regards, Ingwie.

**Comment by starmessage** [comment]
The io.cpccFileSystemMini depends on cpccUnicodeSupport and io.cpccPathHelper
You will probably need io.cpccPathHelper to work with pathnames and fullpathnames, so I guess this dependency does not bother you.
I do not know if the dependency on cpccUnicodeSupport bothers you. If you compile your project as NON-unicode, you will not notice any difference at all. It would be like there is no unicode support at all.

Let me know if this information helps.
Get the latest files from http://code.google.com/p/cpcc/

**Comment by starmessage** [comment]
The updated [cross platform file system class](https://github.com/starmessage/cpcc/blob/master/fs.cpccFileSystem.h) is now a stand-alone (no other dependencies to install), header-only class.
